/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package entity

import "time"

// DefaultPermissions defines the default system permissions
var DefaultPermissions = []Permission{
	// Route permissions
	{
		ID:         "route_create",
		Name:       "Create Route",
		Resource:   "route",
		Action:     "create",
		Desc:       "Permission to create routes",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "route_read",
		Name:       "Read Route",
		Resource:   "route",
		Action:     "read",
		Desc:       "Permission to view routes",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "route_update",
		Name:       "Update Route",
		Resource:   "route",
		Action:     "update",
		Desc:       "Permission to update routes",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "route_delete",
		Name:       "Delete Route",
		Resource:   "route",
		Action:     "delete",
		Desc:       "Permission to delete routes",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "route_list",
		Name:       "List Routes",
		Resource:   "route",
		Action:     "list",
		Desc:       "Permission to list routes",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},

	// Service permissions
	{
		ID:         "service_create",
		Name:       "Create Service",
		Resource:   "service",
		Action:     "create",
		Desc:       "Permission to create services",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "service_read",
		Name:       "Read Service",
		Resource:   "service",
		Action:     "read",
		Desc:       "Permission to view services",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "service_update",
		Name:       "Update Service",
		Resource:   "service",
		Action:     "update",
		Desc:       "Permission to update services",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "service_delete",
		Name:       "Delete Service",
		Resource:   "service",
		Action:     "delete",
		Desc:       "Permission to delete services",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "service_list",
		Name:       "List Services",
		Resource:   "service",
		Action:     "list",
		Desc:       "Permission to list services",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},

	// Upstream permissions
	{
		ID:         "upstream_create",
		Name:       "Create Upstream",
		Resource:   "upstream",
		Action:     "create",
		Desc:       "Permission to create upstreams",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "upstream_read",
		Name:       "Read Upstream",
		Resource:   "upstream",
		Action:     "read",
		Desc:       "Permission to view upstreams",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "upstream_update",
		Name:       "Update Upstream",
		Resource:   "upstream",
		Action:     "update",
		Desc:       "Permission to update upstreams",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "upstream_delete",
		Name:       "Delete Upstream",
		Resource:   "upstream",
		Action:     "delete",
		Desc:       "Permission to delete upstreams",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "upstream_list",
		Name:       "List Upstreams",
		Resource:   "upstream",
		Action:     "list",
		Desc:       "Permission to list upstreams",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},

	// Consumer permissions
	{
		ID:         "consumer_create",
		Name:       "Create Consumer",
		Resource:   "consumer",
		Action:     "create",
		Desc:       "Permission to create consumers",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "consumer_read",
		Name:       "Read Consumer",
		Resource:   "consumer",
		Action:     "read",
		Desc:       "Permission to view consumers",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "consumer_update",
		Name:       "Update Consumer",
		Resource:   "consumer",
		Action:     "update",
		Desc:       "Permission to update consumers",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "consumer_delete",
		Name:       "Delete Consumer",
		Resource:   "consumer",
		Action:     "delete",
		Desc:       "Permission to delete consumers",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "consumer_list",
		Name:       "List Consumers",
		Resource:   "consumer",
		Action:     "list",
		Desc:       "Permission to list consumers",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},

	// SSL permissions
	{
		ID:         "ssl_create",
		Name:       "Create SSL",
		Resource:   "ssl",
		Action:     "create",
		Desc:       "Permission to create SSL certificates",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "ssl_read",
		Name:       "Read SSL",
		Resource:   "ssl",
		Action:     "read",
		Desc:       "Permission to view SSL certificates",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "ssl_update",
		Name:       "Update SSL",
		Resource:   "ssl",
		Action:     "update",
		Desc:       "Permission to update SSL certificates",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "ssl_delete",
		Name:       "Delete SSL",
		Resource:   "ssl",
		Action:     "delete",
		Desc:       "Permission to delete SSL certificates",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "ssl_list",
		Name:       "List SSL",
		Resource:   "ssl",
		Action:     "list",
		Desc:       "Permission to list SSL certificates",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},

	// Plugin permissions
	{
		ID:         "plugin_create",
		Name:       "Create Plugin",
		Resource:   "plugin",
		Action:     "create",
		Desc:       "Permission to create plugins",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "plugin_read",
		Name:       "Read Plugin",
		Resource:   "plugin",
		Action:     "read",
		Desc:       "Permission to view plugins",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "plugin_update",
		Name:       "Update Plugin",
		Resource:   "plugin",
		Action:     "update",
		Desc:       "Permission to update plugins",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "plugin_delete",
		Name:       "Delete Plugin",
		Resource:   "plugin",
		Action:     "delete",
		Desc:       "Permission to delete plugins",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "plugin_list",
		Name:       "List Plugins",
		Resource:   "plugin",
		Action:     "list",
		Desc:       "Permission to list plugins",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},

	// User management permissions
	{
		ID:         "user_create",
		Name:       "Create User",
		Resource:   "user",
		Action:     "create",
		Desc:       "Permission to create users",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "user_read",
		Name:       "Read User",
		Resource:   "user",
		Action:     "read",
		Desc:       "Permission to view users",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "user_update",
		Name:       "Update User",
		Resource:   "user",
		Action:     "update",
		Desc:       "Permission to update users",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "user_delete",
		Name:       "Delete User",
		Resource:   "user",
		Action:     "delete",
		Desc:       "Permission to delete users",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "user_list",
		Name:       "List Users",
		Resource:   "user",
		Action:     "list",
		Desc:       "Permission to list users",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},

	// Role management permissions
	{
		ID:         "role_create",
		Name:       "Create Role",
		Resource:   "role",
		Action:     "create",
		Desc:       "Permission to create roles",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "role_read",
		Name:       "Read Role",
		Resource:   "role",
		Action:     "read",
		Desc:       "Permission to view roles",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "role_update",
		Name:       "Update Role",
		Resource:   "role",
		Action:     "update",
		Desc:       "Permission to update roles",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "role_delete",
		Name:       "Delete Role",
		Resource:   "role",
		Action:     "delete",
		Desc:       "Permission to delete roles",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "role_list",
		Name:       "List Roles",
		Resource:   "role",
		Action:     "list",
		Desc:       "Permission to list roles",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},

	// Audit permissions
	{
		ID:         "audit_read",
		Name:       "Read Audit Logs",
		Resource:   "audit",
		Action:     "read",
		Desc:       "Permission to view audit logs",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
	{
		ID:         "audit_config",
		Name:       "Configure Audit",
		Resource:   "audit",
		Action:     "config",
		Desc:       "Permission to configure audit settings",
		CreateTime: time.Now().Unix(),
		UpdateTime: time.Now().Unix(),
	},
}

// DefaultRoles defines the default system roles
var DefaultRoles = []Role{
	{
		BaseInfo: BaseInfo{
			ID:         "admin",
			CreateTime: time.Now().Unix(),
			UpdateTime: time.Now().Unix(),
		},
		Name:   "Administrator",
		Desc:   "Full system access",
		Status: 1,
		Permissions: []string{
			"route_create", "route_read", "route_update", "route_delete", "route_list",
			"service_create", "service_read", "service_update", "service_delete", "service_list",
			"upstream_create", "upstream_read", "upstream_update", "upstream_delete", "upstream_list",
			"consumer_create", "consumer_read", "consumer_update", "consumer_delete", "consumer_list",
			"ssl_create", "ssl_read", "ssl_update", "ssl_delete", "ssl_list",
			"plugin_create", "plugin_read", "plugin_update", "plugin_delete", "plugin_list",
			"user_create", "user_read", "user_update", "user_delete", "user_list",
			"role_create", "role_read", "role_update", "role_delete", "role_list",
			"audit_read", "audit_config",
		},
	},
	{
		BaseInfo: BaseInfo{
			ID:         "operator",
			CreateTime: time.Now().Unix(),
			UpdateTime: time.Now().Unix(),
		},
		Name:   "Operator",
		Desc:   "Can manage routes, services, and upstreams",
		Status: 1,
		Permissions: []string{
			"route_create", "route_read", "route_update", "route_delete", "route_list",
			"service_create", "service_read", "service_update", "service_delete", "service_list",
			"upstream_create", "upstream_read", "upstream_update", "upstream_delete", "upstream_list",
			"consumer_read", "consumer_list",
			"ssl_read", "ssl_list",
			"plugin_read", "plugin_list",
		},
	},
	{
		BaseInfo: BaseInfo{
			ID:         "viewer",
			CreateTime: time.Now().Unix(),
			UpdateTime: time.Now().Unix(),
		},
		Name:   "Viewer",
		Desc:   "Read-only access to all resources",
		Status: 1,
		Permissions: []string{
			"route_read", "route_list",
			"service_read", "service_list",
			"upstream_read", "upstream_list",
			"consumer_read", "consumer_list",
			"ssl_read", "ssl_list",
			"plugin_read", "plugin_list",
		},
	},
}